Models/ErrorViewModel.cs
using System;

namespace Indie_Art_Sharing_System.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Indie_Art_Sharing_System.Models
{
    public class User
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Contact { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

Controllers/SigninSignupController.cs
using Indie_Art_Sharing_System.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Net;
using System.Net.Mail;

namespace Indie_Art_Sharing_System.Controllers
{
    public class SigninSignupController : Controller
    {
        private readonly ILogger<SigninSignupController> _logger;

        public SigninSignupController(ILogger<SigninSignupController> logger)
        {
            _logger = logger;
        }

        public IActionResult SignIn()
        {
            return View();
        }

        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Complete(User user)
        {
            MailMessage mailMessage = new MailMessage();
            mailMessage.To.Add(user.Email);
            mailMessage.From = new MailAddress("alomhero435@gmail.com");
            mailMessage.Subject = "Verification Code";
            mailMessage.Body = $"Hi {user.Name},\nCongratulations! You are successfully registered on Indie Arts\n\n@Regards from <span style='color: Blue'>Hero Alom</span>";
            mailMessage.IsBodyHtml = true;
            SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587);
            smtp.EnableSsl = true;
            smtp.UseDefaultCredentials = false;
            smtp.Credentials = new NetworkCredential("alomhero435@gmail.com", "Heroalom1122"); ;
            smtp.Send(mailMessage);
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Shared/_LayoutFirst.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Indie Arts</title>
    <!--link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Amatic+SC&family=Lobster+Two&family=Merienda&family=Rajdhani:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="stylesheet" href="~/css/site.css" />
    @await RenderSectionAsync("Stylesheet", required: false);
</head>
<body id="AuthBody">
    <div class="containerBox">
        <h2 style="font-size: 50px; text-align: center; color: black;">@ViewData["Title"]</h2>
        @RenderBody()
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!--script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script-->
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/SigninSignup/Complete.cshtml
@{
    ViewData["Title"] = "Congrats! <br> Your sign up completed";
}

<a asp-controller="SigninSignup" asp-action="Signin" style="font-size: 50px; text-align: center; color: red; margin-left: 70px;">Go to sign in page</a>

Views/SigninSignup/SignIn.cshtml
@{
    ViewData["Title"] = "Sign In";
}

<div class="formBox" style="width: 100%;">
    <form>
        <div class="inputWithIcon">
            <input type="email" name="email" placeholder="Email">
            <i class="far fa-envelope fa-lg fa-fw"></i>
        </div>
        <div class="inputWithIcon" style="margin-bottom: 20px;">
            <input type="password" name="password" placeholder="Password">
            <i class="fa fa-lock fa-lg fa-fw"></i>
        </div>
    </form>
    <button id="signInButton" class="btn authButton">Sign In</button>
    <a class="redirectLink" asp-area="" asp-controller="SigninSignup" asp-action="Signup">Sign Up</a>
</div>

Views/SigninSignup/SignUp.cshtml
@model User
@{
    ViewData["Title"] = "Sign Up";
}

<div class="formBox" style="width: 100%;">
    <form asp-action="Complete" asp-controller="SigninSignup">
        <div class="inputWithIcon">
            <input type="text" name="name" placeholder="Name" asp-for="Name">
            <i class="fa fa-user fa-lg fa-fw"></i>
        </div>
        <div class="inputWithIcon">
            <input type="text" name="contact" placeholder="Contact" asp-for="Contact">
            <i class="fa fa-lock fa-lg fa-fw"></i>
        </div>
        <div class="inputWithIcon">
            <input type="email" name="email" placeholder="Email" asp-for="Email">
            <i class="far fa-envelope fa-lg fa-fw"></i>
        </div>
        <div class="inputWithIcon" style="margin-bottom: 20px;">
            <input type="password" name="password" placeholder="Password" asp-for="Password">
            <i class="fa fa-lock fa-lg fa-fw"></i>
        </div>
        <button asp-area="" asp-controller="SigninSignup" asp-action="Complete" id="signUpButton" class="btn authButton" type="submit">Sign Up</button>
    </form>
    <a class="redirectLink" asp-area="" asp-controller="SigninSignup" asp-action="Signin" style="margin-left: 172px;">Sign In</a>
</div>